/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9ef522849838c641da0cbd0b305931d6)
interface __BaseEnv_Env {
	APPEALS_DB: D1Database;
	AI: Ai;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
