// Real local Pages + D1 integration. Production runs must explicitly supply
// APPEALS_TEST_ALLOW_LIVE=1; every receipt is printed for operator cleanup.
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const origin = process.env.APPEALS_TEST_BASE_URL || 'http://localhost:4188';
if (!['localhost', '127.0.0.1'].includes(new URL(origin).hostname) && process.env.APPEALS_TEST_ALLOW_LIVE !== '1') throw new Error('Live submissions require explicit test opt-in.');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const context = await browser.newContext();
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
async function openAppeal() {
  await page.getByRole('button', { name: '이의제기', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: '이의제기', exact: true });
  await dialog.waitFor();
  assert.equal(await dialog.locator('textarea').count(), 1);
  assert.equal(await dialog.locator('input, select').count(), 0);
  return dialog;
}
try {
  await page.goto(`${origin}/short?subject=hanguksa`);
  await page.getByLabel('단답형 답안').fill('접수 동작 확인용 답안');
  await page.getByRole('button', { name: '채점', exact: true }).click();
  await page.locator('.typed').waitFor();
  const initialUrl = page.url();
  let dialog = await openAppeal();
  assert.equal(page.url(), initialUrl, 'opening a popup preserves the current practice route');
  const draft = '[자동 검증] 이의제기 저장·답안 연결 확인입니다. 검증 후 삭제 대상입니다.';
  await dialog.getByLabel('이의제기 내용', { exact: true }).fill(draft);
  let failedPayload;
  await page.route('**/api/appeals', async route => {
    failedPayload = route.request().postDataJSON();
    await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '검증용 일시 저장 오류' }) });
  });
  await dialog.getByRole('button', { name: '전송', exact: true }).click();
  await dialog.getByRole('alert').filter({ hasText: '검증용 일시 저장 오류' }).waitFor();
  assert.equal(await dialog.getByLabel('이의제기 내용', { exact: true }).inputValue(), draft);
  assert.equal(failedPayload.subject, 'hanguksa');
  assert.equal(failedPayload.context.type, 'short');
  assert.equal(failedPayload.context.submittedAnswer, '접수 동작 확인용 답안');
  assert.equal(failedPayload.context.result.status, 'incorrect');
  assert.match(failedPayload.source, /^\/short\?/);
  assert.equal(new URL(failedPayload.source, origin).searchParams.get('subject'), 'hanguksa');
  assert.equal(failedPayload.category, undefined, 'classification is an API default, not a user input');
  assert.equal(failedPayload.expectedAnswer, undefined);
  await page.unroute('**/api/appeals');
  const received = page.waitForResponse(response => response.url().endsWith('/api/appeals') && response.request().method() === 'POST');
  await dialog.getByRole('button', { name: '전송', exact: true }).click();
  const response = await received;
  assert.equal(response.status(), 201);
  const receipt = await response.json();
  assert.equal(receipt.id, failedPayload.id, 'network retry retains the same idempotency key');
  await dialog.getByRole('status').filter({ hasText: '이의제기를 접수했습니다.' }).waitFor();
  assert.match(await dialog.locator('.appeal-receipt').innerText(), new RegExp(receipt.id));
  console.log(JSON.stringify({ receipt: receipt.id, origin, tests: ['one-input popup', 'question attachment', 'answer and score', 'save failure keeps input', 'idempotent retry', 'D1 receipt'] }));
  await dialog.locator('.appeal-receipt').getByRole('button', { name: '닫기', exact: true }).click();
  await dialog.waitFor({ state: 'hidden' });
  assert.equal(page.url(), initialUrl);
  assert.equal((await context.request.get(`${origin}/api/appeals`)).status(), 405);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${origin}/questions?subject=all&token=must-not-be-attached`);
  dialog = await openAppeal();
  await dialog.getByLabel('이의제기 내용', { exact: true }).fill('확');
  let generalPayload;
  await page.route('**/api/appeals', async route => {
    generalPayload = route.request().postDataJSON();
    await route.fulfill({ status: 201, contentType: 'application/json', body: JSON.stringify({ id: generalPayload.id, received: true }) });
  });
  await dialog.getByRole('button', { name: '전송', exact: true }).click();
  await dialog.getByRole('status').filter({ hasText: '이의제기를 접수했습니다.' }).waitFor();
  assert.equal(generalPayload.subject, 'all');
  assert.equal(generalPayload.message, '확');
  assert.equal(generalPayload.context, null);
  assert.equal(new URL(generalPayload.source, origin).pathname, '/questions');
  assert.equal(new URL(generalPayload.source, origin).searchParams.has('token'), false);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await dialog.locator('.appeal-receipt').getByRole('button', { name: '닫기', exact: true }).click();
  await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
  const card = page.locator('.bank-question').first();
  const selectedId = await card.getAttribute('id');
  await card.getByRole('button', { name: '이 문항 이의제기', exact: true }).click();
  dialog = page.getByRole('dialog', { name: '이의제기', exact: true });
  const colors = await dialog.locator('textarea').evaluate(element => ({ text: getComputedStyle(element).color, bodyText: getComputedStyle(document.body).color, background: getComputedStyle(element).backgroundColor, dialogBackground: getComputedStyle(element.closest('dialog')).backgroundColor }));
  assert.equal(colors.text, colors.bodyText, 'textarea follows the dark theme foreground');
  assert.equal(colors.background, colors.dialogBackground, 'textarea follows the dark theme card background');
  await dialog.getByLabel('이의제기 내용', { exact: true }).fill('선택한 문항 확인');
  await dialog.getByRole('button', { name: '전송', exact: true }).click();
  await dialog.getByRole('status').waitFor();
  assert.equal(generalPayload.context.questionId, selectedId);
  assert.notEqual(generalPayload.subject, 'all', 'a selected bank card sends its actual subject');
  assert.equal(generalPayload.context.submittedAnswer, '', 'a bank card does not attach an unrelated study attempt');
  assert.equal(generalPayload.context.result.status, 'ungraded');
  assert.deepEqual(errors, []);
  console.log('Single-character all-subject feedback, safe source, selected-card context and mobile/dark popup passed (mocked receipts).');
} finally { await context.close(); await browser.close(); }
