// Run against Vite: HISTORY_TEST_BASE_URL=http://127.0.0.1:4187 PLAYWRIGHT_MODULE=/path/to/playwright/index.mjs node tests/history-browser.mjs
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const origin = process.env.HISTORY_TEST_BASE_URL || 'http://127.0.0.1:4187';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const context = await browser.newContext();
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const history = () => page.evaluate(async () => (await import('/src/history-store.js')).historyStore.listAttempts());
const waitCount = count => page.waitForFunction(async count => (await (await import('/src/history-store.js')).historyStore.listAttempts()).length === count, count);
try {
  await page.goto(`${origin}/short?subject=dongyangsa`);
  await page.getByLabel('단답형 답안').fill('틀린 답안');
  await page.getByRole('button', {name:'채점',exact:true}).click();
  await waitCount(1);
  let attempts = await history();
  assert.equal(attempts[0].result.good, false);
  const firstId = attempts[0].questionId;
  const correct = attempts[0].question.answer;
  await page.reload();
  await page.locator('.typed').waitFor();
  assert.equal(await page.locator('.typed').innerText(), '틀린 답안');
  assert.equal((await history()).length, 1);
  await page.getByRole('button', {name:'다시 풀기',exact:true}).click();
  await page.getByLabel('단답형 답안').fill(String(correct));
  await page.getByRole('button', {name:'채점',exact:true}).click();
  await waitCount(2);
  attempts = await history();
  assert.deepEqual(attempts.map(item=>item.result.good).sort(), [false,true]);
  assert.ok(await page.locator('.exam-progress').innerText().then(text=>text.includes('2번째')));
  await page.goto(`${origin}/history`);
  await page.locator('.history-entry').first().waitFor();
  assert.equal(await page.locator('.history-entry').count(), 2);
  await page.getByLabel('결과', {exact:true}).selectOption('correct');
  assert.equal(await page.locator('.history-entry').count(), 1);
  await page.getByRole('link', {name:'새 시도로 다시 풀기'}).click();
  await page.getByLabel('단답형 답안').waitFor();
  assert.equal(new URL(page.url()).searchParams.get('q'), firstId);
  await waitCount(3);
  await page.reload();
  await page.getByLabel('단답형 답안').waitFor();
  assert.equal((await history()).length, 3, 'retry URL reload must not create a fourth attempt');
  await page.getByLabel('단답형 답안').fill('연속 입력한 마지막 답안');
  await page.getByRole('link', {name:'히스토리',exact:true}).click();
  assert.equal((await history()).find(item=>item.attemptNumber===3).value, '연속 입력한 마지막 답안');
  assert.match(await page.getByRole('link', {name:'단답형',exact:true}).getAttribute('href'), /subject=dongyangsa/);
  await page.goto(`${origin}/short?subject=hanguksa`);
  await page.getByLabel('단답형 답안').fill('한국사 별도 답안');
  await page.getByLabel('문항 번호').fill('2');
  await page.getByRole('button', {name:'이동',exact:true}).click();
  await page.getByLabel('단답형 답안').fill('한국사 두 번째 답안');
  const secondId = new URL(page.url()).searchParams.get('q');
  const secondTab = await context.newPage();
  await secondTab.goto(`${origin}/short?subject=hanguksa`);
  await secondTab.getByLabel('단답형 답안').waitFor();
  assert.equal(await secondTab.getByLabel('단답형 답안').inputValue(), '한국사 두 번째 답안');
  assert.equal(await secondTab.getByLabel('문항 번호').inputValue(), '2');
  await page.goto(`${origin}/short?subject=dongyangsa`);
  await page.getByLabel('단답형 답안').waitFor();
  assert.equal(await page.getByLabel('단답형 답안').inputValue(), '연속 입력한 마지막 답안');
  await page.goto(`${origin}/short?subject=hanguksa&q=${encodeURIComponent(secondId)}`);
  await page.getByLabel('단답형 답안').waitFor();
  assert.equal(await page.getByLabel('문항 번호').inputValue(), '2');
  await secondTab.close();
  const storeChecks = await page.evaluate(async () => {
    const {createHistoryStore,HISTORY_TTL_MS} = await import('/src/history-store.js');
    let now=Date.now();
    const store=createHistoryStore({database:'history-transaction-tests',now:()=>now});
    const bank={subject:'hanguksa',type:'essay'};
    const base={...bank,id:'kept',questionId:'q',question:{id:'q',prompt:'질문'},value:'답',result:{total:7,max:10,items:[{id:'r',score:7}]},startedAt:now,updatedAt:now,attemptNumber:1};
    await store.saveAttempt(base,{session:{...bank,questionId:'q',attemptId:'kept',updatedAt:now}});
    await store.saveAttempt({...base,value:'최종 답'});
    const unique=(await store.listAttempts()).length;
    await store.close();
    const restored=await store.loadBank(bank);
    await store.deleteAttempt('kept');
    const lateDeleted=await store.saveAttempt({...base,result:{total:10,max:10}});
    const deleted=await store.loadBank(bank);
    await store.saveAttempt({...base,id:'clear-me'});
    await store.clearHistory();
    const lateClear=await store.saveAttempt({...base,id:'clear-me'});
    const revision=(await store.loadBank(bank)).revision;
    await store.saveAttempt({...base,id:'old',updatedAt:now-HISTORY_TTL_MS},{revision});
    await store.saveAttempt({...base,id:'fresh'},{revision,session:{...bank,questionId:'q',attemptId:'old',updatedAt:now-HISTORY_TTL_MS}});
    const expired=await store.loadBank(bank);
    now+=HISTORY_TTL_MS+1;
    const allExpired=await store.listAttempts();
    await store.close();
    return {unique,restored,lateDeleted,deleted,lateClear,expired,allExpired};
  });
  assert.equal(storeChecks.unique,1);
  assert.equal(storeChecks.restored.attempts[0].value,'최종 답');
  assert.equal(storeChecks.restored.attempts[0].result.items[0].score,7);
  assert.equal(storeChecks.lateDeleted,false);
  assert.equal(storeChecks.deleted.attempts.length,0);
  assert.equal(storeChecks.deleted.session,null);
  assert.equal(storeChecks.lateClear,false);
  assert.deepEqual(storeChecks.expired.attempts.map(item=>item.id),['fresh']);
  assert.equal(storeChecks.expired.session,null);
  assert.equal(storeChecks.allExpired.length,0);
  // Mock scoring transport only: exercise the actual Essay UI and late result persistence without an AI call.
  let releaseScore;
  await page.route('**/api/score', async route => {
    await new Promise(resolve => { releaseScore = resolve; });
    const request=route.request().postDataJSON();
    await route.fulfill({json:{essayId:request.essayId,total:7,max:10,feedback:'검증용 부분점수',items:[{id:'r1',label:'근거',score:7,max:10,comment:'일부 충족',studentQuote:'서술형 보관 답안',evidence:[]}]}});
  });
  async function startEssay() {
    await page.goto(`${origin}/essay?subject=hanguksa`);
    await page.getByLabel('서술형 답안').fill('서술형 보관 답안');
    await page.getByRole('button',{name:'채점',exact:true}).click();
    await page.getByRole('button',{name:'AI API 키',exact:true}).click();
    await page.getByPlaceholder('API 키',{exact:true}).fill('AIza-demo-history-only');
    await page.getByRole('button',{name:'이 모델로 채점',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('.status')?.textContent.includes('채점 중'));
    await page.getByRole('link',{name:'히스토리',exact:true}).click();
  }
  await startEssay();
  while(!releaseScore) await new Promise(resolve=>setTimeout(resolve,5));
  releaseScore();
  await page.waitForFunction(async()=> (await (await import('/src/history-store.js')).historyStore.listAttempts()).some(item=>item.type==='essay'&&item.result?.total===7));
  const scoredEssay=(await history()).find(item=>item.type==='essay');
  assert.equal(scoredEssay.result.items[0].studentQuote,'서술형 보관 답안');
  assert.ok(!JSON.stringify(scoredEssay).includes('AIza-demo'), 'API keys must not enter history');
  await page.goto(`${origin}/essay?subject=hanguksa`);
  await page.getByRole('heading',{name:'7 / 10점',exact:true}).waitFor();
  assert.equal(await page.getByLabel('서술형 답안').inputValue(),'서술형 보관 답안');
  // A late result must finish its original record without stealing a newer retry's resume session.
  await page.getByRole('button',{name:'다시 풀기',exact:true}).click();
  releaseScore=null;
  await startEssay();
  const olderPending=(await history()).find(item=>item.type==='essay'&&!item.result);
  assert.ok(olderPending);
  await page.getByLabel('기록 유형',{exact:true}).selectOption('essay');
  await page.getByLabel('결과',{exact:true}).selectOption('ungraded');
  await page.getByRole('link',{name:'새 시도로 다시 풀기'}).click();
  await page.getByLabel('서술형 답안').fill('늦은 채점 결과보다 최근에 시작한 답안');
  const newer=(await history()).find(item=>item.type==='essay'&&item.id!==olderPending.id&&!item.result);
  assert.ok(newer);
  const beforeLate=(await history()).length;
  while(!releaseScore) await new Promise(resolve=>setTimeout(resolve,5));
  releaseScore();
  await page.waitForFunction(async id=>(await (await import('/src/history-store.js')).historyStore.listAttempts()).some(item=>item.id===id&&item.result?.total===7),olderPending.id);
  await page.reload();
  await page.getByLabel('서술형 답안').waitFor();
  assert.equal(await page.getByLabel('서술형 답안').inputValue(),'늦은 채점 결과보다 최근에 시작한 답안');
  assert.equal((await history()).length,beforeLate,'late result must not reset retry token and create another attempt');
  const resumed=await page.evaluate(async()=>(await import('/src/history-store.js')).historyStore.loadBank({subject:'hanguksa',type:'essay'}));
  assert.equal(resumed.session.attemptId,newer.id);
  await page.getByRole('button',{name:'다시 풀기',exact:true}).click();
  releaseScore=null;
  await startEssay();
  await page.locator('.history-entry').first().waitFor();
  const pending=(await history()).find(item=>item.type==='essay'&&!item.result);
  assert.ok(pending);
  await page.evaluate(async id=>(await import('/src/history-store.js')).historyStore.deleteAttempt(id),pending.id);
  while(!releaseScore) await new Promise(resolve=>setTimeout(resolve,5));
  releaseScore();
  await page.waitForTimeout(100);
  assert.ok(!(await history()).some(item=>item.id===pending.id),'deleted in-flight essay must not resurrect');
  const beforeGuide=(await history()).length;
  await page.goto(`${origin}/guide`);
  for(let i=0;i<3;i++) await page.locator('.guide-dock').getByRole('button',{name:'다음',exact:true}).click();
  await page.waitForTimeout(1800);
  assert.equal((await history()).length,beforeGuide,'guide must never save demonstration answers');
  const blocked=await browser.newContext();
  await blocked.addInitScript(()=>Object.defineProperty(window,'indexedDB',{value:undefined}));
  const blockedPage=await blocked.newPage();
  await blockedPage.goto(`${origin}/short?subject=hanguksa`);
  await blockedPage.getByLabel('단답형 답안').fill('저장 실패에서도 연습 가능');
  assert.ok((await blockedPage.locator('.history-storage-error').innerText()).includes('저장하지 못했습니다'));
  await blocked.close();
  await page.goto(`${origin}/history`);
  await page.locator('.history-entry').first().waitFor();
  await page.getByRole('button',{name:'기록 삭제',exact:true}).first().click();
  await page.getByRole('button',{name:'전체 삭제',exact:true}).click();
  await page.getByRole('button',{name:'모든 기록 삭제',exact:true}).click();
  await waitCount(0);
  assert.deepEqual(errors, []);
  console.log('History browser checks passed: grading/retry idempotency, drafts, new-tab resume, subjects, explicit q, jumps, IDB reopen/upsert/delete/TTL and late-write rejection.');
} finally { await context.close(); await browser.close(); }
